### ISSUE TITLE
Fraction Cover Percentile product fails repeatedly across several years for two tiles.

### ISSUE THREAD

**Issue by tebadi** [opendatacube/odc-stats#141]
When running fractional cover percentile across the archive, it was observed that a couple of tiles failed repeated over several years.  This appears to be due to lack of wofs data over those tiles. Here is the details of failed tiles per year:

1987 {'x40/y57', 'x39/y57'}
1988 {'x40/y57'}
1989 {'x40/y57'}
1990 {'x40/y57'}
1991 {'x40/y57'}
1992 {'x40/y57'}
1993 {'x40/y57'}
1994 {'x40/y57'}
1996 {'x40/y57'}
1997 {'x40/y57'}
2002 {'x40/y57'}
2003 {'x40/y57'}
2005 {'x40/y57'}
2006 {'x40/y57'}
2008 {'x40/y57', 'x39/y57'}
2009 {'x40/y57', 'x39/y57'}

**Comment by emmaai** [comment]
Fixed
