### ISSUE TITLE
Image on GHCR is private and image on Docker Hub is not up-to-date

### ISSUE THREAD

**Issue by vikineema** [opendatacube/odc-stats#148]
The GHCR image is private and the last  update to the publicly available image on Docker Hub was last year which contains odc-stats version 1.0.35.
![image](https://github.com/user-attachments/assets/23ad9bbb-6895-4a3f-96f5-5dcf2bba044b)

**Comment by SpacemanPaul** [comment]
I think @alexgleith is looking into this.

**Comment by alexgleith** [comment]
Made it public now :-)
