### ISSUE TITLE
Update the docker image to use the latest odc-stats version  1.0.33

### ISSUE THREAD

**Issue by vikineema** [opendatacube/odc-stats#87]
The docker image tagged `latest` uses the `odc-stats` version `1.0.32` instead of the latest `odc-stats` version which is `1.0.33`.
`docker container run -it opendatacube/datacube-statistician:latest pip list| grep odc-stats`

`odc-stats                 1.0.32`

**Comment by fangfy** [comment]
Hi @emmaai @SpacemanPaul @omad, it looks like dockerise test failed (https://github.com/opendatacube/odc-stats/actions/runs/4191291551/jobs/7265577644). Any idea why?

**Comment by emmaai** [comment]
The connection is reset by s3. Rerun will fix it.

**Comment by vikineema** [comment]
Hi @emmaai @Spac @omad .  I've tested the latest published [image ](https://hub.docker.com/layers/opendatacube/datacube-statistician/latest/images/sha256-11fea04557e8e61cc068aad47b6e352f818fc9e1edbf3fca87dc7162f8160e22?context=explore) from the [rerun workflow](https://github.com/opendatacube/odc-stats/actions/runs/4191291551) and the odc-stats version is still 1.0.32.  What could be causing this?

**Comment by emmaai** [comment]
had a look, it used the cache available in ecr, since nothing has changed with the files involved in the docker image building.

**Comment by fangfy** [comment]
Hi @emmaai, do you have an estimate of when this can be fixed? we urgently need this new image to generate S2 gm products.

**Comment by jmettes** [comment]
I've been noticing a lot of intermittent failures in tests using external S3 data in odc-tools - especially those using `s3://sentinel-s2-l2a-cogs`. I wonder if that's what's happening here too. I wonder if that bucket recently changed to a less highly-available storage class. Ideally these tests would be replaced with mocks, or locally stored data.

Maybe in the meantime, it's worth trying to set `GDAL_HTTP_MAX_RETRY` somewhere?
https://github.com/rasterio/rasterio/issues/2119#issuecomment-790024225

Apparently max_retry default is 0:
https://gdal.org/user/virtual_file_systems.html

**Comment by emmaai** [comment]
> Hi @emmaai, do you have an estimate of when this can be fixed? we urgently need this new image to generate S2 gm products.

Within this week.

**Comment by emmaai** [comment]
> I've been noticing a lot of intermittent failures in tests using external S3 data in odc-tools - especially those using `s3://sentinel-s2-l2a-cogs`. I wonder if that's what's happening here too. I wonder if that bucket recently changed to a less highly-available storage class. Ideally these tests would be replaced with mocks, or locally stored data.
> 
> Maybe in the meantime, it's worth trying to set `GDAL_HTTP_MAX_RETRY` somewhere? [rasterio/rasterio#2119 (comment)](https://github.com/rasterio/rasterio/issues/2119#issuecomment-790024225)
> 
> Apparently max_retry default is 0: https://gdal.org/user/virtual_file_systems.html

For the test, `GDAL_HTTP_MAX_RETRY` is set here https://github.com/opendatacube/odc-stats/blob/0826115ffc577fc46d9d80b11fa1ae872c3cf61a/docker/docker-compose.yml#L21
and here https://github.com/opendatacube/odc-stats/blob/0826115ffc577fc46d9d80b11fa1ae872c3cf61a/.github/workflows/main.yml#L137

Still, the connection can be reset by s3 server, which can not be caught or retried.

**Comment by emmaai** [comment]
Could you have a look at PR #88, it should resolve the issue.
